### ISSUE TITLE
SAML ID causing errors #1

### ISSUE THREAD

**Issue by nevryn** [GEANT/CAT#87]
# Issue type

- [ X] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
An error is generated when enrolling a new admin if they have a strangely formed ID.
## How to reproduce issue
Login with a UK Federation ID. Enter invitation token.
 
## Detail of issue
PHP Fatal error:  Uncaught Exception: <p>Input validation error: The user identifier is not an ASCII string!</p> in /opt/CAT/web/lib/common/InputValidation.php:247\nStack trace:\n#0 /opt/CAT/web/admin/action_enrollment.php(86): web\\lib\\common\\InputValidation->User(Object(SAML2\\XML\\saml\\NameID))\n#1 {main}\n  thrown in /opt/CAT/web/lib/common/InputValidation.php on line 247

**Comment by restena-sw** [comment]
Can you post the exact value you get for a user ID from your authsource? In your mail it looks like there are newlines in the XML. Our input sanitizer curently chokes on such control characters. 
If that's the case, I'll some (small) sanitisation on the input string so that newline and possibly tabs are only filtered out, not complained about.

**Comment by nevryn** [comment]
On Tue, Sep 05, 2017 at 10:33:23AM +0000, Stefan Winter wrote:
>    Can you post the exact value you get for a user ID from your
>    authsource? In your mail it looks like there are newlines in the XML.
>    Our input sanitizer curently chokes on such control characters.
>    If that's the case, I'll some (small) sanitisation on the input string
>    so that newline and possibly tabs are only filtered out, not complained
>    about.

The two views I have are from the SSP Demo page:

"urn:oid:1.3.6.1.4.1.5923.1.1.1.10	
NameID
XXXXXXXXXXXXXXXXX
Format
urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
NameQualifier
https://idp.jisc.ac.uk/idp/shibboleth
SPNameQualifier
https://cat-beta.govroam.uk/simplesaml/module.php/saml/sp/metadata.php/default-sp"

and from the Javascript code in the page:

<span class='tooltip' style='cursor: pointer;' onclick='alert("<saml:NameID
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
NameQualifier="https://idp.jisc.ac.uk/idp/shibboleth"
SPNameQualifier="https://cat-beta.govroam.uk/simplesaml/module.php/saml/sp/metadata.php/default-sp"
Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">XXXXXXXXXXXXXXXX</saml:NameID>")'>click
to display</span>

If there's another way then let me know and I'll do it.

Thanks,

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
Hm, looks like it (but with browsers, mail programs etc. reformatting things as they see fit it's difficult to be sure).
I'll add the whitespace filter and then you can check again. Regardless, I can always suggest the Firefox plugin "SAMLtracer" which will print you the entire SAML XML blob as received. If there are newlines in that view, they are on the wire.

**Comment by restena-sw** [comment]
I've pushed a commit a few seconds ago - please test.

**Comment by nevryn** [comment]
On Tue, Sep 05, 2017 at 03:46:10AM -0700, Stefan Winter wrote:
>    I've pushed a commit a few seconds ago - please test.

Ok, error message has gone and the invitation sort of works. It looks like
the token has been accepted (i.e. that user is listed as an administrator of
an IdP) but in the 'User Overview' page it doesn't show the user as managing
anything. I also can't add an email address or a name to the user details.
The form submits without error but the information isn't displayed.

Thanks,

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
Can you send a new invitation token? Maybe the "old" name doesn't match the new mangling now...

**Comment by restena-sw** [comment]
Okay, it was a twofold issue. One having to with character escaping on INSERT; the other one with the schema.

This is now fixed in code and schema.sql but in your deployment you still have to allow for more space to store the user ID:

alter table user_options change column `user_id` `user_id` varchar(2048) NOT NULL;

Your user IDs are REALLY long.

**Comment by nevryn** [comment]
On Tue, Sep 05, 2017 at 11:28:50AM +0000, Stefan Winter wrote:
>    Okay, it was a twofold issue. One having to with character escaping on
>    INSERT; the other one with the schema.
> 
>    This is now fixed in code and schema.sql but in your deployment you
>    still have to allow for more space to store the user ID:
> 
>    alter table user_options change column user_id user_id varchar(2048)
>    NOT NULL;
> 
>    Your user IDs are REALLY long.

Tried it with the latest code and the schema change but there's still a
problem. The same as before - put the token in and the user still doesn't
appear to be managing the domain. There's no line in the user_options table
for 'fedadmin' for that user ID.

This in the apache logs:

[Tue Sep 05 13:36:24.420730 2017] [:error] [pid 9328] [client
193.62.24.33:50949] PHP Warning:  print_r(): Invalid State Error in
/opt/CAT/core/DBConnection.php on line 89, referer:
/https://cat-beta.govroam.uk/

repeated lots. 

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
I can confirm that is still foobar'ed. :-)
The user IDs were the only area where input validation and escaping was less thoroughly done than everywhere else - simply because we get known-good info (and without ' and " and <> characters :-) ) from the eduroam SP proxy.
I'm now doing all the prepared statements legwork and we should then have a more consistent treatment across the product. This will take a little while though.

**Comment by restena-sw** [comment]
Humm.
Code-wise, this is mostly fixed. There is one major issue with this: the "ownership" table stores the user -> inst bindings, and has the pair (user,inst) as unique key.

Turns out that for UTF-8 usernames, the max length for the username field in the table is varchar(255). Any attempt to make it longer makes MariaDB/MySQL complain that the resulting unique key would become longer than 767 bytes, which is not allowed.

Unfortunately, the usernames you want to store are longer than 255 bytes.

The only way to fix this is by not making the username/inst pair a unique key. But there are at least two queries which rely on this, one is a INSERT ... ON DUPLICATE KEY UPDATE and one is a INSERT IGNORE.

Both queries need to be profoundly rethought before the key can be made go away. I'm afraid this is not going to work out today.

Until then, feel free to retry this (git pull) and to observe how the creation of the IdP works, but the owner's userid is truncated in the ownership table. The error message will be that the (truncated) userID is not the owner of the newly created IdP.

**Comment by nevryn** [comment]
On Tue, Sep 05, 2017 at 01:59:55PM +0000, Stefan Winter wrote:
>    Humm.
>    Code-wise, this is mostly fixed. There is one major issue with this:
>    the "ownership" table stores the user -> inst bindings, and has the
>    pair (user,inst) as unique key.
> 
>    Turns out that for UTF-8 usernames, the max length for the username
>    field in the table is varchar(255). Any attempt to make it longer makes
>    MariaDB/MySQL complain that the resulting unique key would become
>    longer than 767 bytes, which is not allowed.
> 
>    Unfortunately, the usernames you want to store are longer than 255
>    bytes.
> 
>    The only way to fix this is by not making the username/inst pair a
>    unique key. But there are at least two queries which rely on this, one
>    is a INSERT ... ON DUPLICATE KEY UPDATE and one is a INSERT IGNORE.
> 
>    Both queries need to be profoundly rethought before the key can be made
>    go away. I'm afraid this is not going to work out today.
> 
>    Until then, feel free to retry this (git pull) and to observe how the
>    creation of the IdP works, but the owner's userid is truncated in the
>    ownership table. The error message will be that the (truncated) userID
>    is not the owner of the newly created IdP.

Ok, thanks for letting me know. I might have to drop the use of UK Fed for
now.

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
[UserManagement.diff.zip](https://github.com/GEANT/CAT/files/1280622/UserManagement.diff.zip)

Please try this patch (which alters the two SQL statements in question) and apply the following schema change:

ALTER TABLE ownership DROP KEY `pair`;
ALTER TABLE ownership CHANGE COLUMN `user_id` `user_id` VARCHAR(2048) NOT NULL;

This should give you long enough usernames to fit in the entire XML cruft.

This is not commited/pushed as we are in the middle of updating the codebase on cat-pilot.eduroam.org and I don't want to introduce significant code base shifts right now.

Once I get your confirmation that this actually works, and we're done with the cat-pilot update, this will get into Git.

**Comment by restena-sw** [comment]
That's for core/UserManagement.php obviously

**Comment by restena-sw** [comment]
If this is successful and you use the NameID values as user IDs, I was given a word of warning regarding that mode of operation:
* the XML blob could get re-formatted by the IdP (e.g. during software upgrades)
* the attributes might change (e.g. the SPNameQualifier bit is optional and an IdP might decide to discontinue sending it)

These changes make no material changes to the actual identity, but they result in different strings and thus the perception on the SP side that "it's a different user".

I was also told that SAML software typically has a way of "trimming down" the received value to ONLY the tuple of the content of NameQualifier and the actual value of the NameID, but I cannot give you any indication of how to do that; that would be a question for the simpleSAMLphp mailing list.

Note that this is in no way a buggy feature of the CAT; it's how SAML works - you are just seeing an ugly facet of it. The only thing I can do is make the code "8-bit clean" so that whatever you want to store as a userID, you can.

**Comment by nevryn** [comment]
On Wed, Sep 06, 2017 at 06:18:13AM -0700, Stefan Winter wrote:
>    If this is successful and you use the NameID values as user IDs, I was
>    given a word of warning regarding that mode of operation:
>      * the XML blob could get re-formatted by the IdP (e.g. during
>        software upgrades)
>      * the attributes might change (e.g. the SPNameQualifier bit is
>        optional and an IdP might decide to discontinue sending it)
> 
>    These changes make no material changes to the actual identity, but they
>    result in different strings and thus the perception on the SP side that
>    "it's a different user".

Yep, that seems to be a general idiosyncrasy of using external data sources.

>    I was also told that SAML software typically has a way of "trimming
>    down" the received value to ONLY the tuple of the content of
>    NameQualifier and the actual value of the NameID, but I cannot give you
>    any indication of how to do that; that would be a question for the
>    simpleSAMLphp mailing list.

Thanks, I will see what I can find.

>    Note that this is in no way a buggy feature of the CAT; it's how SAML
>    works - you are just seeing an ugly facet of it. The only thing I can
>    do is make the code "8-bit clean" so that whatever you want to store as
>    a userID, you can.

Don't worry, I understand.

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by nevryn** [comment]
On Wed, Sep 06, 2017 at 02:55:06AM -0700, Stefan Winter wrote:
>    [1]UserManagement.diff.zip
> 
>    Please try this patch (which alters the two SQL statements in question)
>    and apply the following schema change:
> 
>    ALTER TABLE ownership DROP KEY pair;
>    ALTER TABLE ownership CHANGE COLUMN user_id user_id VARCHAR(2048) NOT
>    NULL;
> 
>    This should give you long enough usernames to fit in the entire XML
>    cruft.
> 
>    This is not commited/pushed as we are in the middle of updating the
>    codebase on cat-pilot.eduroam.org and I don't want to introduce
>    significant code base shifts right now.
> 
>    Once I get your confirmation that this actually works, and we're done
>    with the cat-pilot update, this will get into Git.

Yep, that seems to work.

Thanks,

Mike

-- 
Mike Richardson
Currently on Secondment to JISC
*Plain text only please - attachments stripped on arrival*

**Comment by restena-sw** [comment]
SInce we also had more things to push, I included this. So this is now in Git master and the issue is closed.
